#line 2 "src/lex.yy.c"

#line 4 "src/lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 96
#define YY_END_OF_BUFFER 97
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[299] =
    {   0,
       94,   94,   97,   95,   94,   94,   82,   95,    4,   88,
       81,   95,   76,   77,   86,   85,   73,   84,   80,   87,
       40,   40,   74,   70,   89,   75,   90,   93,   37,   37,
       78,   79,   91,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   71,   92,
       72,   83,   94,   69,    0,   47,   46,    0,   55,   72,
       64,   56,    0,    0,   53,   61,   51,   62,   52,   63,
        0,   43,    2,    1,   54,   44,   39,   39,    3,    3,
        3,    3,    3,    3,    3,   40,   79,   71,   78,   60,
       66,   68,   67,   59,   37,    0,    0,   57,   37,   37,

       37,   37,   37,   37,   12,   37,   37,   37,   37,   37,
       37,   20,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   58,   65,    0,    0,   41,   48,    0,
       43,    1,   43,    0,   44,    3,    3,    3,    3,   39,
       39,    3,    3,    0,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,   50,   49,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   18,   37,   21,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,    0,   43,    0,   43,    0,
       44,    3,    3,    3,    3,    3,    3,    3,   42,    3,

        3,    3,    3,    3,    3,    3,    3,    3,    5,   37,
        7,    8,   37,   37,   37,   37,   14,   15,   37,   37,
       19,   22,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   34,   37,   37,    0,   43,   42,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    6,    9,   37,   37,   37,   37,   17,
       37,   37,   25,   37,   37,   37,   37,   37,   37,   32,
       37,   37,   36,   37,   37,   13,   16,   37,   24,   26,
       27,   28,   29,   30,   37,   37,   37,   37,   11,   37,
       31,   37,   37,   10,   23,   33,   35,    0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    6,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   20,   20,   21,   22,   23,
       24,   25,   26,    6,   27,   27,   27,   27,   28,   29,
       30,   30,   30,   30,   30,   31,   30,   30,   30,   30,
       30,   30,   30,   30,   32,   30,   30,   33,   30,   30,
       34,   35,   36,   37,   30,    6,   38,   39,   40,   41,

       42,   43,   44,   45,   46,   30,   47,   48,   49,   50,
       51,   52,   30,   53,   54,   55,   56,   57,   58,   59,
       60,   61,   62,   63,   64,   65,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[66] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    1,    4,    1,    5,    5,    5,
        1,    1,    1,    1,    1,    1,    5,    5,    5,    5,
        5,    5,    5,    1,    1,    1,    1,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[307] =
    {   0,
        0,    0,  617,  618,   64,   66,  592,   67,  618,   49,
       63,  580,  618,  618,  590,   62,  618,   64,   62,   73,
       87,  131,  588,  618,   70,  588,   59,  618,    0,   87,
      618,  618,  587,  554,  556,   63,   53,   50,   62,  557,
       73,  556,  564,   66,  545,  554,  552,  557,  618,   75,
      618,  618,  123,  618,  125,  117,  618,  598,  618,  618,
      618,  618,  118,  128,  618,  618,  618,  618,  618,  618,
      584,  138,  618,    0,  618,  164,  157,  114,  121,  181,
      184,  190,  223,  199,  205,    0,  618,  618,  618,  575,
      618,  618,  618,  574,    0,  139,  562,  618,  541,  553,

      540,  555,  542,  548,  534,  535,  532,  532,  535,  529,
      516,    0,  507,  510,  110,  508,  111,  132,  512,  505,
      144,  174,  510,  618,  618,  143,  552,  618,  618,  214,
      618,    0,  239,  256,  618,  259,  265,  274,  279,  226,
      282,    0,  285,  289,  300,  305,  314,  320,  326,  357,
      280,  334,  337,  344,  618,  618,  503,  515,  510,  498,
      194,  512,  510,  505,  497,  503,  506,    0,  492,    0,
      498,  494,  481,  483,  485,  492,  469,  459,  454,  462,
      447,  436,  440,  438,  426,  340,  383,  352,  618,  360,
      389,  397,  363,  403,  420,  423,  426,  429,  432,    0,

      285,  166,  224,  180,  440,  447,  465,  468,    0,  426,
        0,    0,  415,  423,  408,  414,    0,    0,  403,  399,
        0,    0,  382,  382,  378,  388,  377,  381,  385,  384,
      378,  361,  366,    0,  351,  362,  471,  474,  618,  198,
        0,  363,  345,  294,  360,  339,  482,  488,  492,  500,
      507,  510,  513,    0,    0,  323,  321,  307,  297,    0,
      287,  285,    0,  280,  271,  255,  234,  243,  244,    0,
      223,  214,    0,  183,  182,    0,    0,  193,    0,    0,
        0,    0,    0,    0,  183,  149,  123,  126,    0,  111,
        0,  120,  103,    0,    0,    0,    0,  618,  563,  568,

      570,  131,  575,  580,  112,   71
    } ;

static const flex_int16_t yy_def[307] =
    {   0,
      298,    1,  298,  298,  298,  298,  298,  299,  298,  298,
      298,  300,  298,  298,  298,  298,  298,  298,  298,  298,
      301,  301,  298,  298,  298,  298,  298,  298,  302,  302,
      298,  298,  298,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  298,  298,
      298,  298,  298,  298,  299,  303,  298,  299,  298,  298,
      298,  298,  300,  300,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  304,  298,  298,   22,   77,  305,  305,
      305,  305,  305,  305,  305,   22,  298,  298,  298,  298,
      298,  298,  298,  298,  302,  299,  300,  298,  302,  302,

      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  298,  298,  303,  303,  298,  298,  298,
      298,  304,  298,  298,  298,  305,  305,  305,  305,   77,
       77,  306,  305,  298,  306,  305,  305,  305,  305,  306,
       83,  305,  305,  305,  298,  298,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  298,  298,  298,  298,  298,
      298,  305,  305,  305,  305,  305,  305,  305,  298,  306,

      306,  306,  306,  306,  305,  305,  305,  305,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  298,  298,  298,  306,
      306,  306,  306,  306,  306,  306,  305,  305,  305,  305,
      305,  305,  305,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,    0,  298,  298,

      298,  298,  298,  298,  298,  298
    } ;

static const flex_int16_t yy_nxt[684] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   22,
       23,   24,   25,   26,   27,   28,   29,   29,   29,   29,
       30,   29,   29,   31,    4,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   29,   41,   29,   42,   29,   29,
       29,   29,   43,   44,   45,   46,   47,   48,   29,   29,
       29,   49,   50,   51,   52,   53,   53,   53,   53,   56,
       61,   57,   59,   60,   66,  142,   88,   71,   68,   72,
       72,   72,   93,   94,   73,   67,   62,   69,   70,   74,
       89,   96,   90,   91,  104,   97,   75,  106,  124,  107,

      101,   58,   76,  105,   77,   77,   78,  102,  108,  109,
      116,  117,  110,  103,   80,  112,  143,   81,   82,   83,
      118,   57,  113,  119,   53,   53,  128,   56,   80,   57,
      298,  140,  140,  141,   84,   95,   63,  125,  142,  142,
      142,   56,   85,   57,  297,   83,   76,   57,   86,   86,
       86,  127,   64,  172,  175,   72,   72,   72,   80,   58,
      296,   81,   82,  295,  173,  130,  131,  294,  131,  177,
      293,  176,   80,   58,   77,   77,   78,  127,   84,  130,
      131,  133,  133,  133,  178,  131,   85,  136,  137,  181,
      292,  134,  135,  144,  135,  144,  242,  182,  145,  145,

      145,  142,  142,  142,  138,  134,  135,  142,  142,  142,
      245,  135,  139,  243,  146,  147,  142,  142,  142,  183,
      148,  184,  142,  142,  142,  291,  186,  246,  186,  241,
      147,  187,  187,  187,  290,  153,  289,  149,  288,  147,
      150,  150,  150,  140,  140,  141,  152,  213,  214,  151,
      151,  151,  154,  241,  147,  241,  133,  133,  133,  287,
      151,  151,  151,  151,  151,  151,  188,  189,  190,  189,
      190,  244,  286,  191,  191,  191,  142,  142,  142,  241,
      188,  189,  142,  142,  142,  285,  189,  284,  283,  192,
      193,  142,  142,  142,  282,  194,  142,  142,  142,  141,

      141,  141,  142,  142,  142,  193,  199,  199,  199,  197,
      205,  206,  195,  281,  193,  240,  241,  145,  145,  145,
      280,  196,  142,  142,  142,  241,  198,  207,  200,  193,
      200,  142,  142,  142,  279,  208,  147,  142,  142,  142,
      241,  278,  200,  142,  142,  142,  277,  200,  276,  241,
      147,  142,  142,  142,  142,  142,  142,  187,  187,  187,
      147,  142,  142,  142,  237,  147,  237,  147,  275,  238,
      238,  238,  274,  147,  150,  150,  150,  191,  191,  191,
      142,  142,  142,  150,  150,  150,  241,  201,  202,  147,
      241,  147,  241,  241,  150,  150,  150,  150,  150,  150,

      187,  187,  187,  273,  203,  272,  191,  191,  191,  271,
      270,  131,  204,  131,  142,  142,  142,  135,  269,  135,
      142,  142,  142,  268,  267,  131,  266,  265,  193,  264,
      131,  135,  263,  193,  262,  261,  135,  142,  142,  142,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  199,
      199,  199,  193,  260,  193,  259,  193,  142,  142,  142,
      239,  258,  239,  257,  142,  142,  142,  193,  256,  255,
      247,  248,  254,  236,  239,  235,  193,  249,  193,  239,
      234,  233,  142,  142,  142,  142,  142,  142,  238,  238,
      238,  238,  238,  238,  250,  248,  248,  232,  252,  142,

      142,  142,  189,  231,  189,  142,  142,  142,  230,  142,
      142,  142,  251,  248,  229,  253,  189,  142,  142,  142,
      248,  189,  248,  228,  142,  142,  142,  142,  142,  142,
      142,  142,  142,  227,  226,  225,  224,  248,  248,  223,
      248,  222,  221,  220,  219,  218,  217,  248,  216,  215,
      212,  211,  210,  209,  298,  185,  180,  179,  174,  171,
      248,  170,  248,   55,   55,   55,   55,   55,   63,   63,
      169,   63,   63,   79,   79,  126,  126,  126,  126,  126,
      132,  168,  132,  132,  132,  167,  166,  165,  164,  163,
      162,  161,  160,  159,  158,  157,   64,  156,  155,  129,

      298,  123,  122,  121,  120,  115,  114,  111,  100,   99,
       98,   92,   87,   65,   64,   54,  298,    3,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298
    } ;

static const flex_int16_t yy_chk[684] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    5,    6,    6,    8,
       11,    8,   10,   10,   16,  306,   25,   19,   18,   19,
       19,   19,   27,   27,   20,   16,   11,   18,   18,   20,
       25,   30,   25,   25,   37,   30,   20,   38,   50,   38,

       36,    8,   21,   37,   21,   21,   21,   36,   38,   39,
       44,   44,   39,   36,   21,   41,  305,   21,   21,   21,
       44,   56,   41,   44,   53,   53,   63,   55,   21,   55,
       64,   78,   78,   78,   21,  302,   64,   50,   79,   79,
       79,   96,   21,   96,  293,   21,   22,  126,   22,   22,
       22,   56,   63,  115,  117,   72,   72,   72,   22,   55,
      292,   22,   22,  290,  115,   72,   72,  288,   72,  118,
      287,  117,   22,   96,   77,   77,   77,  126,   22,   72,
       72,   76,   76,   76,  118,   72,   22,   77,   77,  121,
      286,   76,   76,   80,   76,   80,  202,  121,   80,   80,

       80,   81,   81,   81,   77,   76,   76,   82,   82,   82,
      204,   76,   77,  202,   81,   81,   84,   84,   84,  122,
       82,  122,   85,   85,   85,  285,  130,  204,  130,  240,
       84,  130,  130,  130,  278,   85,  275,   82,  274,   81,
       83,   83,   83,  140,  140,  140,   84,  161,  161,   83,
       83,   83,   85,  240,   84,  203,  133,  133,  133,  272,
       83,   83,   83,   83,   83,   83,  133,  133,  134,  133,
      134,  203,  271,  134,  134,  134,  136,  136,  136,  203,
      133,  133,  137,  137,  137,  269,  133,  268,  267,  136,
      136,  138,  138,  138,  266,  137,  139,  139,  139,  141,

      141,  141,  143,  143,  143,  138,  144,  144,  144,  139,
      151,  151,  137,  265,  136,  201,  201,  145,  145,  145,
      264,  138,  146,  146,  146,  244,  139,  151,  145,  138,
      145,  147,  147,  147,  262,  151,  146,  148,  148,  148,
      201,  261,  145,  149,  149,  149,  259,  145,  258,  244,
      148,  152,  152,  152,  153,  153,  153,  186,  186,  186,
      146,  154,  154,  154,  188,  152,  188,  153,  257,  188,
      188,  188,  256,  149,  150,  150,  150,  190,  190,  190,
      193,  193,  193,  150,  150,  150,  246,  150,  150,  152,
      245,  154,  243,  242,  150,  150,  150,  150,  150,  150,

      187,  187,  187,  236,  150,  235,  191,  191,  191,  233,
      232,  187,  150,  187,  192,  192,  192,  191,  231,  191,
      194,  194,  194,  230,  229,  187,  228,  227,  192,  226,
      187,  191,  225,  194,  224,  223,  191,  195,  195,  195,
      196,  196,  196,  197,  197,  197,  198,  198,  198,  199,
      199,  199,  192,  220,  196,  219,  197,  205,  205,  205,
      199,  216,  199,  215,  206,  206,  206,  195,  214,  213,
      205,  205,  210,  185,  199,  184,  198,  206,  196,  199,
      183,  182,  207,  207,  207,  208,  208,  208,  237,  237,
      237,  238,  238,  238,  206,  205,  207,  181,  208,  247,

      247,  247,  238,  180,  238,  248,  248,  248,  179,  249,
      249,  249,  207,  247,  178,  208,  238,  250,  250,  250,
      207,  238,  249,  177,  251,  251,  251,  252,  252,  252,
      253,  253,  253,  176,  175,  174,  173,  247,  251,  172,
      252,  171,  169,  167,  166,  165,  164,  250,  163,  162,
      160,  159,  158,  157,  127,  123,  120,  119,  116,  114,
      253,  113,  251,  299,  299,  299,  299,  299,  300,  300,
      111,  300,  300,  301,  301,  303,  303,  303,  303,  303,
      304,  110,  304,  304,  304,  109,  108,  107,  106,  105,
      104,  103,  102,  101,  100,   99,   97,   94,   90,   71,

       58,   48,   47,   46,   45,   43,   42,   40,   35,   34,
       33,   26,   23,   15,   12,    7,    3,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[97] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "src/lexer.l"
#line 2 "src/lexer.l"
#include <helper.h>
#include <y.tab.h>

void displayLexer(int token, const char* text);
int check_type();
void lexicalError(const char* message, ...);
int errorCount = 0;

#line 731 "src/lex.yy.c"
/* Add error patterns */
#line 733 "src/lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 27 "src/lexer.l"

#line 952 "src/lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 299 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 618 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 28 "src/lexer.l"
{ /* Single-line comment: ignore */ }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 29 "src/lexer.l"
{ comment(); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 32 "src/lexer.l"
{
    lexicalError("Invalid identifier '%s' - cannot start with digit", yytext);
    displayLexer(INVALID_ID, yytext);
    yylval.nice = strdup(yytext);
    return ERROR;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 39 "src/lexer.l"
{
    lexicalError("Invalid character '%s' in input", yytext);
    displayLexer(INVALID_CHAR, yytext);
    yylval.nice = strdup("INVALID CHARACTER");
    return ERROR;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 46 "src/lexer.l"
{ displayLexer(AUTO, yytext);      yylval.nice = strdup(getTokenName(AUTO));      return AUTO; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 47 "src/lexer.l"
{ displayLexer(BREAK, yytext);     yylval.nice = strdup(getTokenName(BREAK));     return BREAK; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 48 "src/lexer.l"
{ displayLexer(CASE, yytext);      yylval.nice = strdup(getTokenName(CASE));      return CASE; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 49 "src/lexer.l"
{ displayLexer(CHAR, yytext);      yylval.nice = strdup(getTokenName(CHAR));      return CHAR; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 50 "src/lexer.l"
{ displayLexer(CONST, yytext);     yylval.nice = strdup(getTokenName(CONST));     return CONST; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 51 "src/lexer.l"
{ displayLexer(CONTINUE, yytext);  yylval.nice = strdup(getTokenName(CONTINUE));  return CONTINUE; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 52 "src/lexer.l"
{ displayLexer(DEFAULT, yytext);   yylval.nice = strdup(getTokenName(DEFAULT));   return DEFAULT; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 53 "src/lexer.l"
{ displayLexer(DO, yytext);        yylval.nice = strdup(getTokenName(DO));        return DO; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 54 "src/lexer.l"
{ displayLexer(DOUBLE, yytext);    yylval.nice = strdup(getTokenName(DOUBLE));    return DOUBLE; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 55 "src/lexer.l"
{ displayLexer(ELSE, yytext);      yylval.nice = strdup(getTokenName(ELSE));      return ELSE; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 56 "src/lexer.l"
{ displayLexer(ENUM, yytext);      yylval.nice = strdup(getTokenName(ENUM));      return ENUM; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 57 "src/lexer.l"
{ displayLexer(EXTERN, yytext);    yylval.nice = strdup(getTokenName(EXTERN));    return EXTERN; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 58 "src/lexer.l"
{ displayLexer(FLOAT, yytext);     yylval.nice = strdup(getTokenName(FLOAT));     return FLOAT; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 59 "src/lexer.l"
{ displayLexer(FOR, yytext);       yylval.nice = strdup(getTokenName(FOR));       return FOR; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 60 "src/lexer.l"
{ displayLexer(GOTO, yytext);      yylval.nice = strdup(getTokenName(GOTO));      return GOTO; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 61 "src/lexer.l"
{ displayLexer(IF, yytext);        yylval.nice = strdup(getTokenName(IF));        return IF; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 62 "src/lexer.l"
{ displayLexer(INT, yytext);       yylval.nice = strdup(getTokenName(INT));       return INT; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 63 "src/lexer.l"
{ displayLexer(LONG, yytext);      yylval.nice = strdup(getTokenName(LONG));      return LONG; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 64 "src/lexer.l"
{ displayLexer(REGISTER, yytext);  yylval.nice = strdup(getTokenName(REGISTER));  return REGISTER; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 65 "src/lexer.l"
{ displayLexer(RETURN, yytext);    yylval.nice = strdup(getTokenName(RETURN));    return RETURN; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 66 "src/lexer.l"
{ displayLexer(SHORT, yytext);     yylval.nice = strdup(getTokenName(SHORT));     return SHORT; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 67 "src/lexer.l"
{ displayLexer(SIGNED, yytext);    yylval.nice = strdup(getTokenName(SIGNED));    return SIGNED; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 68 "src/lexer.l"
{ displayLexer(SIZEOF, yytext);    yylval.nice = strdup(getTokenName(SIZEOF));    return SIZEOF; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 69 "src/lexer.l"
{ displayLexer(STATIC, yytext);    yylval.nice = strdup(getTokenName(STATIC));    return STATIC; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 70 "src/lexer.l"
{ displayLexer(STRUCT, yytext);    yylval.nice = strdup(getTokenName(STRUCT));    return STRUCT; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 71 "src/lexer.l"
{ displayLexer(SWITCH, yytext);    yylval.nice = strdup(getTokenName(SWITCH));    return SWITCH; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 72 "src/lexer.l"
{ displayLexer(TYPEDEF, yytext);   yylval.nice = strdup(getTokenName(TYPEDEF));   return TYPEDEF; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 73 "src/lexer.l"
{ displayLexer(UNION, yytext);     yylval.nice = strdup(getTokenName(UNION));     return UNION; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 74 "src/lexer.l"
{ displayLexer(UNSIGNED, yytext);  yylval.nice = strdup(getTokenName(UNSIGNED));  return UNSIGNED; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 75 "src/lexer.l"
{ displayLexer(VOID, yytext);      yylval.nice = strdup(getTokenName(VOID));      return VOID; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 76 "src/lexer.l"
{ displayLexer(VOLATILE, yytext);  yylval.nice = strdup(getTokenName(VOLATILE));  return VOLATILE; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 77 "src/lexer.l"
{ displayLexer(WHILE, yytext);     yylval.nice = strdup(getTokenName(WHILE));     return WHILE; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 80 "src/lexer.l"
{
    displayLexer(IDENTIFIER, yytext);
    yylval.nice = strdup(yytext);
    return IDENTIFIER;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 87 "src/lexer.l"
{ displayLexer(CONSTANT, yytext); yylval.nice = strdup(yytext); return CONSTANT; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 88 "src/lexer.l"
{ displayLexer(CONSTANT, yytext); yylval.nice = strdup(yytext); return CONSTANT; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 89 "src/lexer.l"
{ displayLexer(CONSTANT, yytext); yylval.nice = strdup(yytext); return CONSTANT; }
	YY_BREAK
case 41:
/* rule 41 can match eol */
YY_RULE_SETUP
#line 90 "src/lexer.l"
{ displayLexer(CONSTANT, yytext); yylval.nice = strdup(yytext); return CONSTANT; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 91 "src/lexer.l"
{ displayLexer(CONSTANT, yytext); yylval.nice = strdup(yytext); return CONSTANT; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 92 "src/lexer.l"
{ displayLexer(CONSTANT, yytext); yylval.nice = strdup(yytext); return CONSTANT; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 93 "src/lexer.l"
{ displayLexer(CONSTANT, yytext); yylval.nice = strdup(yytext); return CONSTANT; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 96 "src/lexer.l"
{
    lexicalError("Invalid octal constant '%s'", yytext);
    displayLexer(INVALID_OCT, yytext);
    yylval.nice = strdup("INVALID OCTAL");
    return ERROR;
}
	YY_BREAK
case 46:
/* rule 46 can match eol */
YY_RULE_SETUP
#line 104 "src/lexer.l"
{ displayLexer(STRING_LITERAL, yytext); yylval.nice = strdup(getTokenName(STRING_LITERAL)); return STRING_LITERAL; }
	YY_BREAK
case 47:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 107 "src/lexer.l"
{
    lexicalError("Unterminated string literal '%s'", yytext);
    displayLexer(UNTERM_STRING, yytext);
    yylval.nice = strdup("UNTERMINATED STRING");
    return ERROR;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 115 "src/lexer.l"
{ displayLexer(ELLIPSIS, yytext);    yylval.nice = strdup(getTokenName(ELLIPSIS));    return ELLIPSIS; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 116 "src/lexer.l"
{ displayLexer(RIGHT_ASSIGN, yytext); yylval.nice = strdup(getTokenName(RIGHT_ASSIGN)); return RIGHT_ASSIGN; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 117 "src/lexer.l"
{ displayLexer(LEFT_ASSIGN, yytext);  yylval.nice = strdup(getTokenName(LEFT_ASSIGN));  return LEFT_ASSIGN; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 118 "src/lexer.l"
{ displayLexer(ADD_ASSIGN, yytext);   yylval.nice = strdup(getTokenName(ADD_ASSIGN));   return ADD_ASSIGN; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 119 "src/lexer.l"
{ displayLexer(SUB_ASSIGN, yytext);   yylval.nice = strdup(getTokenName(SUB_ASSIGN));   return SUB_ASSIGN; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 120 "src/lexer.l"
{ displayLexer(MUL_ASSIGN, yytext);   yylval.nice = strdup(getTokenName(MUL_ASSIGN));   return MUL_ASSIGN; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 121 "src/lexer.l"
{ displayLexer(DIV_ASSIGN, yytext);   yylval.nice = strdup(getTokenName(DIV_ASSIGN));   return DIV_ASSIGN; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 122 "src/lexer.l"
{ displayLexer(MOD_ASSIGN, yytext);   yylval.nice = strdup(getTokenName(MOD_ASSIGN));   return MOD_ASSIGN; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 123 "src/lexer.l"
{ displayLexer(AND_ASSIGN, yytext);   yylval.nice = strdup(getTokenName(AND_ASSIGN));   return AND_ASSIGN; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 124 "src/lexer.l"
{ displayLexer(XOR_ASSIGN, yytext);   yylval.nice = strdup(getTokenName(XOR_ASSIGN));   return XOR_ASSIGN; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 125 "src/lexer.l"
{ displayLexer(OR_ASSIGN, yytext);    yylval.nice = strdup(getTokenName(OR_ASSIGN));    return OR_ASSIGN; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 126 "src/lexer.l"
{ displayLexer(RIGHT_OP, yytext);     yylval.nice = strdup(getTokenName(RIGHT_OP));     return RIGHT_OP; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 127 "src/lexer.l"
{ displayLexer(LEFT_OP, yytext);      yylval.nice = strdup(getTokenName(LEFT_OP));      return LEFT_OP; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 128 "src/lexer.l"
{ displayLexer(INC_OP, yytext);       yylval.nice = strdup(getTokenName(INC_OP));       return INC_OP; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 129 "src/lexer.l"
{ displayLexer(DEC_OP, yytext);       yylval.nice = strdup(getTokenName(DEC_OP));       return DEC_OP; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 130 "src/lexer.l"
{ displayLexer(PTR_OP, yytext);       yylval.nice = strdup(getTokenName(PTR_OP));       return PTR_OP; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 131 "src/lexer.l"
{ displayLexer(AND_OP, yytext);       yylval.nice = strdup(getTokenName(AND_OP));       return AND_OP; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 132 "src/lexer.l"
{ displayLexer(OR_OP, yytext);        yylval.nice = strdup(getTokenName(OR_OP));        return OR_OP; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 133 "src/lexer.l"
{ displayLexer(LE_OP, yytext);        yylval.nice = strdup(getTokenName(LE_OP));        return LE_OP; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 134 "src/lexer.l"
{ displayLexer(GE_OP, yytext);        yylval.nice = strdup(getTokenName(GE_OP));        return GE_OP; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 135 "src/lexer.l"
{ displayLexer(EQ_OP, yytext);        yylval.nice = strdup(getTokenName(EQ_OP));        return EQ_OP; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 136 "src/lexer.l"
{ displayLexer(NE_OP, yytext);        yylval.nice = strdup(getTokenName(NE_OP));        return NE_OP; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 139 "src/lexer.l"
{ displayLexer(SEMICOLON, yytext);    yylval.nice = strdup(getTokenName(SEMICOLON));    return SEMICOLON; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 140 "src/lexer.l"
{ displayLexer(LEFT_BRACE, yytext);   yylval.nice = strdup(getTokenName(LEFT_BRACE));   return LEFT_BRACE; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 141 "src/lexer.l"
{ displayLexer(RIGHT_BRACE, yytext);  yylval.nice = strdup(getTokenName(RIGHT_BRACE));  return RIGHT_BRACE; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 142 "src/lexer.l"
{ displayLexer(COMMA, yytext);        yylval.nice = strdup(getTokenName(COMMA));        return COMMA; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 143 "src/lexer.l"
{ displayLexer(COLON, yytext);        yylval.nice = strdup(getTokenName(COLON));        return COLON; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 144 "src/lexer.l"
{ displayLexer(ASSIGN, yytext);       yylval.nice = strdup(getTokenName(ASSIGN));       return ASSIGN; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 145 "src/lexer.l"
{ displayLexer(LEFT_PAREN, yytext);   yylval.nice = strdup(getTokenName(LEFT_PAREN));   return LEFT_PAREN; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 146 "src/lexer.l"
{ displayLexer(RIGHT_PAREN, yytext);  yylval.nice = strdup(getTokenName(RIGHT_PAREN));  return RIGHT_PAREN; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 147 "src/lexer.l"
{ displayLexer(LEFT_BRACKET, yytext); yylval.nice = strdup(getTokenName(LEFT_BRACKET)); return LEFT_BRACKET; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 148 "src/lexer.l"
{ displayLexer(RIGHT_BRACKET, yytext);yylval.nice = strdup(getTokenName(RIGHT_BRACKET));return RIGHT_BRACKET; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 149 "src/lexer.l"
{ displayLexer(DOT, yytext);          yylval.nice = strdup(getTokenName(DOT));          return DOT; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 150 "src/lexer.l"
{ displayLexer(AMPERSAND, yytext);    yylval.nice = strdup(getTokenName(AMPERSAND));    return AMPERSAND; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 151 "src/lexer.l"
{ displayLexer(EXCLAMATION, yytext);  yylval.nice = strdup(getTokenName(EXCLAMATION));  return EXCLAMATION; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 152 "src/lexer.l"
{ displayLexer(TILDE, yytext);        yylval.nice = strdup(getTokenName(TILDE));        return TILDE; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 153 "src/lexer.l"
{ displayLexer(MINUS, yytext);        yylval.nice = strdup(getTokenName(MINUS));        return MINUS; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 154 "src/lexer.l"
{ displayLexer(PLUS, yytext);         yylval.nice = strdup(getTokenName(PLUS));         return PLUS; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 155 "src/lexer.l"
{ displayLexer(ASTERISK, yytext);     yylval.nice = strdup(getTokenName(ASTERISK));     return ASTERISK; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 156 "src/lexer.l"
{ displayLexer(SLASH, yytext);        yylval.nice = strdup(getTokenName(SLASH));        return SLASH; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 157 "src/lexer.l"
{ displayLexer(PERCENT, yytext);      yylval.nice = strdup(getTokenName(PERCENT));      return PERCENT; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 158 "src/lexer.l"
{ displayLexer(LESS_THAN, yytext);    yylval.nice = strdup(getTokenName(LESS_THAN));    return LESS_THAN; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 159 "src/lexer.l"
{ displayLexer(GREATER_THAN, yytext); yylval.nice = strdup(getTokenName(GREATER_THAN)); return GREATER_THAN; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 160 "src/lexer.l"
{ displayLexer(CARET, yytext);        yylval.nice = strdup(getTokenName(CARET));        return CARET; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 161 "src/lexer.l"
{ displayLexer(PIPE, yytext);         yylval.nice = strdup(getTokenName(PIPE));         return PIPE; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 162 "src/lexer.l"
{ displayLexer(QUESTION, yytext);     yylval.nice = strdup(getTokenName(QUESTION));     return QUESTION; }
	YY_BREAK
case 94:
/* rule 94 can match eol */
YY_RULE_SETUP
#line 164 "src/lexer.l"
{ }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 165 "src/lexer.l"
{}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 167 "src/lexer.l"
ECHO;
	YY_BREAK
#line 1529 "src/lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 299 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 299 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 298);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 167 "src/lexer.l"


int yywrap(void) {
    return 1;
}

void comment() {
    // char c, c1;

    // while (1) {
    //     while ((c = input()) != '*' && c != 0) {
    //         if (c == '\n') {
    //             // Handle new lines if needed
    //         }
    //         putchar(c);
    //     }

    //     if (c == 0) {
    //         // End of file within comment
    //         break;
    //     }

    //     c1 = input();
    //     if (c1 == '/') {
    //         putchar(c1);
    //         break;
    //     } else if (c1 == 0) {
    //         // End of file
    //         break;
    //     } else {
    //         unput(c1);
    //         putchar(c); // put the '*' back.
    //     }
    // }
}

void displayLexer(int token, const char* text) {
    static int first_call = 1;
    if (first_call) {
        printf("+----------------------+----------------------+\n");
        printf("| %-20s | %-20s |\n", "Token", "Text");
        printf("+----------------------+----------------------+\n");
        first_call = 0;
    }
    printf("| %-20s | %-20s |\n", getTokenName(token), text);
}

/* Add this function at the end */
void lexicalError(const char* message, ...) {
    va_list args;
    va_start(args, message);
    fprintf(stderr, "Lexical error at line %d: ", yylineno);
    vfprintf(stderr, message, args);
    fprintf(stderr, "\n");
    va_end(args);
    errorCount++;
}
